#!/usr/bin/perl -w
#
#   Script para correr el parser generado por Happy
#   Autor: German Leon
#

my $x             = 'LexBrainiac.x';
my $y             = 'SinBrainiac.y';
my $lexer         = 'LexBrainiac.hs';
my $parser        = 'SinBrainiac.hs';
my $lexer_test    = 'LexBrainiacTest.hs';
my $parser_test   = 'SinBrainiacTest.hs';
my $brainiac_file = $ARGV[0];

system("alex -g $x");
system("ghc -o LexBrainiacTest --make $lexer $lexer_test");
system("./LexBrainiacTest < $brainiac_file");
