#!/usr/bin/perl -w
#
#   Script para correr el parser generado por Happy
#   Autor: German Leon
#

my $x             = 'LexBrainiac.x';
my $lexer         = 'LexBrainiac.hs';

my $y             = 'SinBrainiac.y';
my $parser        = 'SinBrainiac.hs';
my $parser_test   = 'SinBrainiacTest.hs';

my $impresor      = 'Impresor.hs';

my $brainiac_file = $ARGV[0];

system("alex -g $x");
system("happy -a -g -c $y");
system("ghc -w -fglasgow-exts -o SinBrainiacTest --make $impresor $parser $parser_test");
system("./SinBrainiacTest < $brainiac_file");
