#!/usr/bin/perl -w
#
#   Script para correr el lexer generado por Alex
#   Autor: German Leon
#

my $x             = 'LexBrainiac.x';
my $lexer         = 'LexBrainiac.hs';
my $lexer_test    = 'LexBrainiacTest.hs';
my $brainiac_file = $ARGV[0];

system("alex -g $x");
system("ghc -w -o LexBrainiacTest --make $lexer $lexer_test");
system("./LexBrainiacTest < $brainiac_file");
