#!/usr/bin/perl -w
#
#   Script para correr un programa en Brainiac
#   Autor: German Leon
#

my $x             = 'LexBrainiac.x';
my $lexer         = 'LexBrainiac.hs';

my $y             = 'SinBrainiac.y';
my $parser        = 'SinBrainiac.hs';

my $context           = 'ContBrainiac.hs';
my $context_test      = 'ContBrainiacTest.hs';
my $context_test_exec = 'ContBrainiacTest';

my $tabla = 'TablaSim.hs';
my $cinta = 'Cinta.hs';

my $brainiac           = 'Brainiac.hs';
my $brainiac_test      = 'BrainiacTest.hs';
my $brainiac_test_exec = 'BrainiacTest';

my $brainiac_file = $ARGV[0];

system("alex -g $x") unless (-e $lexer);
system("happy -a -g -c $y") unless (-e $parser);
unless (-e $brainiac_test_exec) {
    system("ghc -w -fglasgow-exts -o BrainiacTest --make " .
     " $brainiac $brainiac_test $context $cinta $tabla");
}
system("./BrainiacTest < $brainiac_file");
