#!/usr/bin/perl -w
#
#   Script para correr el analizador de contexto
#   Autor: German Leon
#

my $x             = 'LexBrainiac.x';
my $lexer         = 'LexBrainiac.hs';

my $y             = 'SinBrainiac.y';
my $parser        = 'SinBrainiac.hs';

my $context       = 'ContBrainiac.hs';
my $context_test  = 'ContBrainiacTest.hs';

my $brainiac_file = $ARGV[0];

system("alex -g $x");
system("happy -a -g -c $y");
system("ghc -w -fglasgow-exts -o ContBrainiacTest --make $context $context_test");
system("./ContBrainiacTest < $brainiac_file");
